defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:password"]
  # To obtain password:
  # sudo apt-get install apache2-utils
  # htpasswd -nb admin secure_password

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "synkx@hotmail.fr"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

[acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0

[acme.httpChallenge]
  entryPoint = "http"