defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$xOZ6iPoL$As9vJB85uPhWjk4dA3RZR."]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "synkx@hotmail.fr"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

[acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0

[acme.httpChallenge]
  entryPoint = "http"